"""add_user_table_and_relationships

Revision ID: 9cbc1ee4eec5
Revises: f5b7a8e9c4d2
Create Date: 2025-03-20 19:18:09.412030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cbc1ee4eec5'
down_revision: Union[str, None] = 'f5b7a8e9c4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_transitions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mood_transitions', 'users', ['user_id'], ['id'])
    op.add_column('spotify_playlists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'spotify_playlists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spotify_playlists', type_='foreignkey')
    op.drop_column('spotify_playlists', 'user_id')
    op.drop_constraint(None, 'mood_transitions', type_='foreignkey')
    op.drop_column('mood_transitions', 'user_id')
    # ### end Alembic commands ###
